apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-oa0s
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-oa0s@sha256:34eaff6da08be932ed74facc8429a91e787d474630453fac72290807dc3efbc1
        name: my-nodejs
        resources: {}
status: {}
